# Generated by Django 2.2.6 on 2019-10-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('service', models.CharField(max_length=50)),
            ],
        ),
    ]
